[package]
name = "chatting_server"
version = "0.1.0"
authors = ["wooq <wooq@nhnnext.org>"]

[dependencies.client]
path = "../components/client"

[dependencies.event_handler]
path = "../components/event_handler"