[package]
name = "chatting_client"
version = "0.1.0"
authors = ["wooq <wooq@nhnnext.org>"]

[dependencies]
bincode = "*"
rustc-serialize = "*"

[dependencies.client]
path = "../components/client"

[dependencies.header]
path = "../components/header"